version: 2
updates:
  # Single npm configuration for all groups
  - package-ecosystem: 'npm'
    directory: '/' # Root directory for the npm packages
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '04:00'
      timezone: 'Etc/UTC'
    groups:
      # Group 1: Core runtime dependencies for Next.js and React
      runtime:
        patterns:
          - 'next'
          - 'react'
          - 'react-dom'
          - 'react-is'

      # Group 2: MUI and Emotion dependencies
      mui-emotion:
        patterns:
          - '@mui/**'
          - '@emotion/**'

      # Group 3: Development tools and linters
      dev-tools:
        patterns:
          - 'eslint*'
          - 'prettier'
          - 'typescript'
          - '@typescript-eslint/**'
          - 'webpack'

      # Group 4: Other npm dependencies
      other-dependencies:
        patterns:
          - '*' # Matches all dependencies
        exclude-patterns:
          - 'next'
          - 'react'
          - 'react-dom'
          - 'react-is'
          - '@mui/**'
          - '@emotion/**'
          - 'eslint*'
          - 'prettier'
          - 'typescript'
          - '@typescript-eslint/**'
          - 'webpack'

    commit-message:
      prefix: '[dependabot]'

  # Separate configuration for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/' # Root directory for GitHub Actions
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[dependabot][github-actions]'
