language: node_js
node_js:
  - 12
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    branch: main
