version: 2.1
orbs:
  yarn: itinerisltd/yarn@2.1.1
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - yarn/test-if-changed:
          run-command: tryBuild
          paths: ./src
      - heroku/deploy-via-git:
          requires:
            - yarn/test-if-changed
          filters:
            branches:
              only: main
