version: 2.1
orbs:
  yarn: itinerisltd/yarn@2.1.1
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - yarn/test-if-changed:
          git_base_branch: origin/main
          except_branches: 'qa'
          run-command: build
          paths: ./src
